name: komb_encontro
description: Organização do evento.
# main: web\main.dart
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  provider: ^6.0.5
  url_launcher: 
  carousel_slider: ^4.0.0


flutter:
  assets:
    - lib/img/kombismo_branco2.png
    - lib/img/old3.jpg
    - lib\carrosel\branca1.jpeg
    - lib\carrosel\branca2.jpeg
    - lib\carrosel\azul.jpeg
    - lib\carrosel\preta.jpeg

    - lib\patrocinadores\IORA.jpeg
    - lib\patrocinadores\laserdj.jpg
    - lib\patrocinadores\tarab.jpg
    - lib\patrocinadores\ambioeste.jpg
    - lib\patrocinadores\dalla.jpeg
    - lib\patrocinadores\delivery.jpeg
    - lib\patrocinadores\santochopp.jpeg

  fonts:
    - family: Fresh Press
      fonts:
        - asset: lib\fontes\fresca.ttf
    - family: Stencil
      fonts:
        - asset: lib\fontes\stencil.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0  
